#!/bin/sh
### BEGIN INIT INFO
# Provides:          lcdshowip
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Log time stamps for OS start and stop
# Description:       Show IP of eth0 and wlan0 on LCD if 
#                    attached to i2c
### END INIT INFO

case "$1" in
  start)
    /home/pi/bin/lcdshowip
    ;;
esac
